### ISSUE TITLE
notify_future needs to be resolved on the disconnect callback

### ISSUE THREAD

**Issue by bdraco** [kaechele/bonaparte#103]
https://github.com/kaechele/bonaparte/blob/73280db4186f1565f2471a0dd9c18bfa0a0175cb/src/bonaparte/device.py#L305

The future should probably set an exception on disconnect so it doesn't block forever

**Comment by kaechele** [comment]
Thanks! That makes sense. I have pushed a possible fix to a branch that I'm going to test hopefully later today.
